
language: generic

dist: trusty
sudo: required

cache:
    apt: true

compiler:
    - gcc
    - clang

matrix:
    include:
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test


script:
    - mkdir build && cd build
    - cmake ..
    - make all

before_install:

    - sudo apt-get -qq update
    - sudo apt-get install -y libnoise-dev
    - sudo add-apt-repository -y ppa:pyglfw/pyglfw && sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends libglfw3-dev libxrandr-dev libxi-dev libxxf86vm-dev libxcursor
    - mkdir gl3w
    - cd gl3w
    - wget https://github.com/skaslev/gl3w/archive/master.zip 
    - unzip master.zip
    - cd gl3w-master
    - python3 gl3w_gen.py
    - mkdir build
    - cd build
    - cmake ..
    - make
    - sudo make install
    - cd ..
    - cd ..
    - cd ..
    - mkdir anttweakbar
    - cd anttweakbar
    - wget 'https://sourceforge.net/projects/anttweakbar/files/AntTweakBar_116.zip' 
    - unzip AntTweakBar_116.zip
    - cd AntTweakBar
    - cd src
    - make
    - cd ..
    - cd include 
    - sudo cp AntTweakBar.h /usr/local/include
    - cd ..
    - cd lib
    - sudo cp libAntTweakBar.so /usr/local/lib/
    - cd ..
    - cd ..
    - cd ..
    
